<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$(MSBuildThisFileDirectory)..\..\common\oni-mod.props" />

  <PropertyGroup>
    <AssemblyName>MotionSensorRange</AssemblyName>
    <RootNamespace>MotionSensorRange</RootNamespace>
    <Version>1.1.0</Version>
  </PropertyGroup>

  <Import Project="$(MSBuildThisFileDirectory)..\..\common\oni-mod.targets" />

</Project>
